2013-09-23 10:30:48,716 ERROR:django.request: Internal Server Error: /ajax/is_pass_valid/
Traceback (most recent call last):
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/dh_site/dowant/ajax/views_ajax.py", line 70, in is_pass_valid
    if(user.check_password(password)):
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 304, in check_password
    return check_password(raw_password, self.password, setter)
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 43, in check_password
    hasher = get_hasher(algorithm)
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 116, in get_hasher
    "setting?" % algorithm)
ValueError: Unknown password hashing algorithm ''. Did you specify it in the PASSWORD_HASHERS setting?ValueError: Unknown password hashing algorithm ''. Did you specify it in the PASSWORD_HASHERS setting?2013-09-23 10:30:48,867 ERROR:django.request: Internal Server Error: /ajax/is_pass_valid/
Traceback (most recent call last):
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/dh_site/dowant/ajax/views_ajax.py", line 70, in is_pass_valid
    if(user.check_password(password)):
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 304, in check_password
    return check_password(raw_password, self.password, setter)
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 43, in check_password
    hasher = get_hasher(algorithm)
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 116, in get_hasher
    "setting?" % algorithm)
ValueError: Unknown password hashing algorithm ''. Did you specify it in the PASSWORD_HASHERS setting?
2013-09-23 10:30:49,101 ERROR:dowant.mobile.views: Unable to get delivery fee info for Xue Hua Mian Dian
2013-09-23 10:30:48,716 ERROR:django.request: Internal Server Error: /ajax/is_pass_valid/
Traceback (most recent call last):
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/opt/dh_site/dowant/ajax/views_ajax.py", line 70, in is_pass_valid
    if(user.check_password(password)):
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 304, in check_password
    return check_password(raw_password, self.password, setter)
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 43, in check_password
    hasher = get_hasher(algorithm)
  File "/opt/venvs/deliveryhero_venv/local/lib/python2.7/site-packages/django/contrib/auth/hashers.py", line 116, in get_hasher
    "setting?" % algorithm)
ValueError: Unknown password hashing algorithm ''. Did you specify it in the PASSWORD_HASHERS setting?
